name: ragamuffin
description: A tool for querying and updating a local database of documents.
version: 0.1.0
repository: https://github.com/ragamuffin-ai/ragamuffin

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.7.0
  crypto: ^3.0.6
  openai_dart: ^0.4.5
  sqlite3: ^2.7.6
  vector_math: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
