name: ragamuffin
description: A tool for querying and updating a local database of documents.
version: 0.2.0
repository: https://github.com/ragamuffin-ai/ragamuffin
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.7.0
  crypto: ^3.0.6
  dartantic_ai: ^0.5.0
  logging: ^1.3.0
  sqlite3: ^2.7.6
  vector_math: ^2.2.0

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  test: ^1.24.0
